version: '3.1'
services:
    wordpress:
        image: wordpress:latest
        links:
        - mariadb:mysql
        environment:
        - WORDPRESS_DB_PASSWORD=password
        - WORDPRESS_DB_USER=root
        ports:
        - 80:80
        volumes:
        - wordpress_data:/var/www/html
        - apm_data:/opt
        - php-config:/usr/local/etc/php
    mariadb:
        image: mariadb:latest
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress
        volumes:
        - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
  apm_data:
  php-config: